include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  PLATFORM: amd64
  TARGET: dev,run
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: bash -ic 'ros2 launch carla_ros_bridge carla_ros_bridge.launch.py'
  ENABLE_INDUSTRIAL_CI: 'false'
  LABEL_MAINTAINER: 'Institute for Automotive Engineering (ika), RWTH Aachen University <
  LABEL_AUTHORS: 'Institute for Automotive Engineering (ika), RWTH Aachen University <