include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: gitlab.ika.rwth-aachen.de:5050/fb-fi/simulation/carla/carla-ros-bridge/base:ubuntu22-jazzy-not-from-src-amd64
  COMMAND: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py
  TARGET: dev,run
  PLATFORM: amd64
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  DISABLE_ROS_INSTALLATION: 'true'
  ENABLE_INDUSTRIAL_CI: 'false' # ONLY TEMPORARY! Remove as soon as issue relating to Flake8 is fixed

.test:
  variables:
    DOCKER_RUN_OPTS: -u root:root -e SCENARIO_RUNNER_PATH='.' # industrial_ci tests launch files which require this env var to at least be set