include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros:noetic
  COMMAND: roslaunch carla_ros_bridge carla_ros_bridge.launch
  TARGET: dev,run
  PLATFORM: amd64
  IMAGE_TAG: ros1
  ADDITIONAL_PIP_FILE: docker/additional-pip-requirements-ros1.txt
  ENABLE_INDUSTRIAL_CI: 'true'

.test:
  variables:
    DOCKER_RUN_OPTS: -u root:root -e SCENARIO_RUNNER_PATH='.' # industrial_ci tests launch files which require this env var to at least be set