include:
  - project: fb-fi/ops/docker-ros
    ref: feature/docker-compose-variable
    file: templates/.gitlab-ci.template.yml

variables:
  DISABLE_INDUSTRIAL_CI: 'true' # ONLY TEMPORARY! Remove as soon as issue relating to Flake8 is fixed
  DISABLE_ARCH_ARM64: 'true'
  DOCKER_COMPOSE_FILE: docker-compose-ros2.yml
  IMAGE_DEV_TARGET: ${CI_REGISTRY_IMAGE}:ros2-dev
  IMAGE_RUN_TARGET: ${CI_REGISTRY_IMAGE}:ros2
  PUSH_AS_LATEST: 'true'

.test:
  variables:
    DOCKER_RUN_OPTS: -u root:root -e SCENARIO_RUNNER_PATH='.' # industrial_ci tests launch files which require this env var to at least be set
