include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:foxy
  COMMAND: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py
  TARGET: dev,run
  PLATFORM: amd64
  IMAGE_TAG: ros2
  ENABLE_INDUSTRIAL_CI: 'false' # ONLY TEMPORARY! Remove as soon as issue relating to Flake8 is fixed
  PUSH_AS_LATEST: 'true'

.test:
  variables:
    DOCKER_RUN_OPTS: -u root:root -e SCENARIO_RUNNER_PATH='.' # industrial_ci tests launch files which require this env var to at least be set