x-base-image: &base-image gitlab.ika.rwth-aachen.de:5050/fb-fi/ops/docker-base/ros2:foxy
x-dev-image:  &dev-image  gitlab.ika.rwth-aachen.de:5050/fb-fi/simulation/carla/ros-bridge/ros2:latest-dev
x-run-image:  &run-image  gitlab.ika.rwth-aachen.de:5050/fb-fi/simulation/carla/ros-bridge/ros2:latest
x-command:    &command    bash -ic "ros2 launch carla_ros_bridge carla_ros_bridge.launch.py"

# ==============================================================================

x-build: &build
  dockerfile: ./docker/docker-ros/Dockerfile
  context: ../
  args:
    BASE_IMAGE: *base-image
    COMMAND: *command
    GIT_HTTPS_USER: $GIT_HTTPS_USER
    GIT_HTTPS_PASSWORD: $GIT_HTTPS_PASSWORD

services:
  dev:
    image: *dev-image
    build:
      target: dev
      <<: *build
  run:
    image: *run-image
    build:
      target: run
      <<: *build
